// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package queries

import (
	"context"
	"time"
)

const latestReadingBefore = `-- name: LatestReadingBefore :one
SELECT recorded_at
FROM telemetry.sensor_readings
WHERE sscc = $1
  AND recorded_at < $2
ORDER BY recorded_at DESC
LIMIT 1
`

type LatestReadingBeforeParams struct {
	Sscc   string
	Before time.Time
}

func (q *Queries) LatestReadingBefore(ctx context.Context, arg LatestReadingBeforeParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestReadingBefore, arg.Sscc, arg.Before)
	var recorded_at time.Time
	err := row.Scan(&recorded_at)
	return recorded_at, err
}

const readingsBetween = `-- name: ReadingsBetween :many
SELECT recorded_at, sscc, device_id, temperature_celsius, humidity_percent, latitude, longitude, received_at
FROM telemetry.sensor_readings
WHERE sscc = $1
  AND recorded_at >= $2
  AND recorded_at < $3
ORDER BY recorded_at, device_id
`

type ReadingsBetweenParams struct {
	Sscc     string
	FromTime time.Time
	Before   time.Time
}

// Readings of an SSCC in [from, before), oldest first; devices break ties in a fixed order.
func (q *Queries) ReadingsBetween(ctx context.Context, arg ReadingsBetweenParams) ([]TelemetrySensorReading, error) {
	rows, err := q.db.Query(ctx, readingsBetween, arg.Sscc, arg.FromTime, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetrySensorReading
	for rows.Next() {
		var i TelemetrySensorReading
		if err := rows.Scan(
			&i.RecordedAt,
			&i.Sscc,
			&i.DeviceID,
			&i.TemperatureCelsius,
			&i.HumidityPercent,
			&i.Latitude,
			&i.Longitude,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
