// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"
)

type TelemetrySensorReading struct {
	RecordedAt         time.Time
	Sscc               string
	DeviceID           string
	TemperatureCelsius float64
	HumidityPercent    *float64
	Latitude           float64
	Longitude          float64
	ReceivedAt         time.Time
}
