// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package queries

import (
	"context"
	"time"
)

const minuteBuckets = `-- name: MinuteBuckets :many
SELECT time_bucket(INTERVAL '1 minute', recorded_at)::timestamptz AS bucket,
       avg(temperature_celsius)::numeric AS avg_temperature_celsius,
       min(temperature_celsius)::numeric AS min_temperature_celsius,
       max(temperature_celsius)::numeric AS max_temperature_celsius,
       count(*) AS reading_count
FROM telemetry.sensor_readings
WHERE sscc = $1
  AND recorded_at >= $2
  AND recorded_at < $3
GROUP BY bucket
ORDER BY bucket
`

type MinuteBucketsParams struct {
	Sscc     string
	FromTime time.Time
	Before   time.Time
}

type MinuteBucketsRow struct {
	Bucket                time.Time
	AvgTemperatureCelsius float64
	MinTemperatureCelsius float64
	MaxTemperatureCelsius float64
	ReadingCount          int64
}

// Average, minimum, and maximum temperature per minute in [from, before), oldest first.
func (q *Queries) MinuteBuckets(ctx context.Context, arg MinuteBucketsParams) ([]MinuteBucketsRow, error) {
	rows, err := q.db.Query(ctx, minuteBuckets, arg.Sscc, arg.FromTime, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MinuteBucketsRow
	for rows.Next() {
		var i MinuteBucketsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.AvgTemperatureCelsius,
			&i.MinTemperatureCelsius,
			&i.MaxTemperatureCelsius,
			&i.ReadingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quarterHourBuckets = `-- name: QuarterHourBuckets :many
SELECT bucket::timestamptz AS bucket,
       avg_temperature_celsius::numeric AS avg_temperature_celsius,
       min_temperature_celsius::numeric AS min_temperature_celsius,
       max_temperature_celsius::numeric AS max_temperature_celsius,
       reading_count::bigint AS reading_count
FROM telemetry.sensor_readings_15m
WHERE sscc = $1
  AND bucket >= $2
  AND bucket < $3
ORDER BY bucket
`

type QuarterHourBucketsParams struct {
	Sscc     string
	FromTime interface{}
	Before   interface{}
}

type QuarterHourBucketsRow struct {
	Bucket                time.Time
	AvgTemperatureCelsius float64
	MinTemperatureCelsius float64
	MaxTemperatureCelsius float64
	ReadingCount          int64
}

// The 15-minute aggregate in [from, before), oldest first.
func (q *Queries) QuarterHourBuckets(ctx context.Context, arg QuarterHourBucketsParams) ([]QuarterHourBucketsRow, error) {
	rows, err := q.db.Query(ctx, quarterHourBuckets, arg.Sscc, arg.FromTime, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuarterHourBucketsRow
	for rows.Next() {
		var i QuarterHourBucketsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.AvgTemperatureCelsius,
			&i.MinTemperatureCelsius,
			&i.MaxTemperatureCelsius,
			&i.ReadingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
