// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type TelemetryShipmentProjection struct {
	Sscc                 string
	ShipmentID           uuid.UUID
	OwnerTenantID        uuid.UUID
	ParticipantTenantIds []uuid.UUID
	AssignedDriverID     *uuid.UUID
	Status               string
	Gtin                 string
	ProductName          string
	LotNumber            string
	MinTempCelsius       float64
	MaxTempCelsius       float64
	LastEventSequence    int32
	UpdatedAt            time.Time
}
