// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projection.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const advance = `-- name: Advance :execrows
UPDATE telemetry.shipment_projection
SET status = $1,
    last_event_sequence = $2,
    participant_tenant_ids = CASE
        WHEN $3::uuid IS NULL
            OR $3::uuid = ANY (participant_tenant_ids) THEN participant_tenant_ids
        ELSE array_append(participant_tenant_ids, $3::uuid)
    END,
    assigned_driver_id = CASE
        WHEN $4::boolean THEN $5::uuid
        ELSE assigned_driver_id
    END,
    updated_at = now()
WHERE sscc = $6
  AND last_event_sequence < $2
`

type AdvanceParams struct {
	Status           string
	Sequence         int32
	JoinedTenantID   *uuid.UUID
	ChangeDriver     bool
	AssignedDriverID *uuid.UUID
	Sscc             string
}

// Applies an event that follows the last applied one: the new status, a tenant that joined, and a driver
// assignment that started or ended. Events at or below the last applied sequence change nothing.
func (q *Queries) Advance(ctx context.Context, arg AdvanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, advance,
		arg.Status,
		arg.Sequence,
		arg.JoinedTenantID,
		arg.ChangeDriver,
		arg.AssignedDriverID,
		arg.Sscc,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createShipment = `-- name: CreateShipment :execrows
INSERT INTO telemetry.shipment_projection (
    sscc, shipment_id, owner_tenant_id, participant_tenant_ids, assigned_driver_id, status, gtin, product_name,
    lot_number, min_temp_celsius, max_temp_celsius, last_event_sequence)
VALUES (
    $1, $2, $3, $4::uuid[], $5, $6,
    $7, $8, $9, $10, $11, $12)
ON CONFLICT (sscc) DO NOTHING
`

type CreateShipmentParams struct {
	Sscc                 string
	ShipmentID           uuid.UUID
	OwnerTenantID        uuid.UUID
	ParticipantTenantIds []uuid.UUID
	AssignedDriverID     *uuid.UUID
	Status               string
	Gtin                 string
	ProductName          string
	LotNumber            string
	MinTempCelsius       float64
	MaxTempCelsius       float64
	Sequence             int32
}

// A shipment delivered twice is created once.
func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, createShipment,
		arg.Sscc,
		arg.ShipmentID,
		arg.OwnerTenantID,
		arg.ParticipantTenantIds,
		arg.AssignedDriverID,
		arg.Status,
		arg.Gtin,
		arg.ProductName,
		arg.LotNumber,
		arg.MinTempCelsius,
		arg.MaxTempCelsius,
		arg.Sequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShipment = `-- name: GetShipment :one
SELECT sscc, shipment_id, owner_tenant_id, participant_tenant_ids, assigned_driver_id, status, gtin, product_name,
       lot_number, min_temp_celsius, max_temp_celsius, last_event_sequence, updated_at
FROM telemetry.shipment_projection
WHERE sscc = $1
`

func (q *Queries) GetShipment(ctx context.Context, sscc string) (TelemetryShipmentProjection, error) {
	row := q.db.QueryRow(ctx, getShipment, sscc)
	var i TelemetryShipmentProjection
	err := row.Scan(
		&i.Sscc,
		&i.ShipmentID,
		&i.OwnerTenantID,
		&i.ParticipantTenantIds,
		&i.AssignedDriverID,
		&i.Status,
		&i.Gtin,
		&i.ProductName,
		&i.LotNumber,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.LastEventSequence,
		&i.UpdatedAt,
	)
	return i, err
}

const lastEventSequence = `-- name: LastEventSequence :one
SELECT last_event_sequence
FROM telemetry.shipment_projection
WHERE sscc = $1
`

func (q *Queries) LastEventSequence(ctx context.Context, sscc string) (int32, error) {
	row := q.db.QueryRow(ctx, lastEventSequence, sscc)
	var last_event_sequence int32
	err := row.Scan(&last_event_sequence)
	return last_event_sequence, err
}

const lockShipments = `-- name: LockShipments :many
SELECT sscc, shipment_id, owner_tenant_id, participant_tenant_ids, assigned_driver_id, status, gtin, product_name,
       lot_number, min_temp_celsius, max_temp_celsius, last_event_sequence, updated_at
FROM telemetry.shipment_projection
WHERE sscc = ANY (CAST($1::text[] AS bpchar[]))
ORDER BY sscc
FOR SHARE
`

// Reads the projections of a detector batch and keeps their status from changing until the transaction ends.
// The rows are locked in SSCC order.
func (q *Queries) LockShipments(ctx context.Context, ssccs []string) ([]TelemetryShipmentProjection, error) {
	rows, err := q.db.Query(ctx, lockShipments, ssccs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetryShipmentProjection
	for rows.Next() {
		var i TelemetryShipmentProjection
		if err := rows.Scan(
			&i.Sscc,
			&i.ShipmentID,
			&i.OwnerTenantID,
			&i.ParticipantTenantIds,
			&i.AssignedDriverID,
			&i.Status,
			&i.Gtin,
			&i.ProductName,
			&i.LotNumber,
			&i.MinTempCelsius,
			&i.MaxTempCelsius,
			&i.LastEventSequence,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
