// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const extendIncident = `-- name: ExtendIncident :execrows
UPDATE telemetry.cold_chain_incidents
SET extreme_temperature_celsius = $1,
    updated_at = now()
WHERE id = $2
  AND ended_at IS NULL
`

type ExtendIncidentParams struct {
	ExtremeTemperatureCelsius float64
	ID                        uuid.UUID
}

func (q *Queries) ExtendIncident(ctx context.Context, arg ExtendIncidentParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendIncident, arg.ExtremeTemperatureCelsius, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertIncident = `-- name: InsertIncident :execrows
INSERT INTO telemetry.cold_chain_incidents (
    id, sscc, shipment_id, device_id, started_at, confirmed_at, min_temp_celsius, max_temp_celsius,
    trigger_temperature_celsius, extreme_temperature_celsius, latitude, longitude, incident_hash)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13)
ON CONFLICT (sscc, started_at) DO NOTHING
`

type InsertIncidentParams struct {
	ID                        uuid.UUID
	Sscc                      string
	ShipmentID                uuid.UUID
	DeviceID                  string
	StartedAt                 time.Time
	ConfirmedAt               time.Time
	MinTempCelsius            float64
	MaxTempCelsius            float64
	TriggerTemperatureCelsius float64
	ExtremeTemperatureCelsius float64
	Latitude                  float64
	Longitude                 float64
	IncidentHash              string
}

// A breach confirmed again, when a batch is processed again, is inserted once.
func (q *Queries) InsertIncident(ctx context.Context, arg InsertIncidentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIncident,
		arg.ID,
		arg.Sscc,
		arg.ShipmentID,
		arg.DeviceID,
		arg.StartedAt,
		arg.ConfirmedAt,
		arg.MinTempCelsius,
		arg.MaxTempCelsius,
		arg.TriggerTemperatureCelsius,
		arg.ExtremeTemperatureCelsius,
		arg.Latitude,
		arg.Longitude,
		arg.IncidentHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestIncident = `-- name: LatestIncident :one
SELECT id, sscc, shipment_id, device_id, started_at, confirmed_at, ended_at, min_temp_celsius, max_temp_celsius, trigger_temperature_celsius, extreme_temperature_celsius, latitude, longitude, duration_seconds, incident_hash, created_at, updated_at
FROM telemetry.cold_chain_incidents
WHERE sscc = $1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) LatestIncident(ctx context.Context, sscc string) (TelemetryColdChainIncident, error) {
	row := q.db.QueryRow(ctx, latestIncident, sscc)
	var i TelemetryColdChainIncident
	err := row.Scan(
		&i.ID,
		&i.Sscc,
		&i.ShipmentID,
		&i.DeviceID,
		&i.StartedAt,
		&i.ConfirmedAt,
		&i.EndedAt,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.TriggerTemperatureCelsius,
		&i.ExtremeTemperatureCelsius,
		&i.Latitude,
		&i.Longitude,
		&i.DurationSeconds,
		&i.IncidentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveAtShipmentEnd = `-- name: ResolveAtShipmentEnd :one
UPDATE telemetry.cold_chain_incidents i
SET ended_at = e.ended_at,
    duration_seconds = floor(extract(epoch FROM e.ended_at - i.started_at))::integer,
    updated_at = now()
FROM (
    SELECT o.id,
           GREATEST(o.confirmed_at, COALESCE((
               SELECT max(r.recorded_at)
               FROM telemetry.sensor_readings r
               WHERE r.sscc = o.sscc
                 AND r.recorded_at >= o.started_at
                 AND r.recorded_at <= $1::timestamptz), o.confirmed_at)) AS ended_at
    FROM telemetry.cold_chain_incidents o
    WHERE o.sscc = $2
      AND o.ended_at IS NULL
) e
WHERE i.id = e.id
  AND i.ended_at IS NULL
RETURNING i.id, i.sscc, i.shipment_id, i.device_id, i.started_at, i.confirmed_at, i.ended_at, i.min_temp_celsius, i.max_temp_celsius, i.trigger_temperature_celsius, i.extreme_temperature_celsius, i.latitude, i.longitude, i.duration_seconds, i.incident_hash, i.created_at, i.updated_at
`

type ResolveAtShipmentEndParams struct {
	Until time.Time
	Sscc  string
}

// Resolves the open incident of a shipment that is no longer monitored, at its last reading recorded until the
// shipment left monitoring (never before the confirmation).
func (q *Queries) ResolveAtShipmentEnd(ctx context.Context, arg ResolveAtShipmentEndParams) (TelemetryColdChainIncident, error) {
	row := q.db.QueryRow(ctx, resolveAtShipmentEnd, arg.Until, arg.Sscc)
	var i TelemetryColdChainIncident
	err := row.Scan(
		&i.ID,
		&i.Sscc,
		&i.ShipmentID,
		&i.DeviceID,
		&i.StartedAt,
		&i.ConfirmedAt,
		&i.EndedAt,
		&i.MinTempCelsius,
		&i.MaxTempCelsius,
		&i.TriggerTemperatureCelsius,
		&i.ExtremeTemperatureCelsius,
		&i.Latitude,
		&i.Longitude,
		&i.DurationSeconds,
		&i.IncidentHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveIncident = `-- name: ResolveIncident :execrows
UPDATE telemetry.cold_chain_incidents
SET ended_at = $1,
    duration_seconds = $2,
    extreme_temperature_celsius = $3,
    updated_at = now()
WHERE id = $4
  AND ended_at IS NULL
`

type ResolveIncidentParams struct {
	EndedAt                   *time.Time
	DurationSeconds           *int32
	ExtremeTemperatureCelsius float64
	ID                        uuid.UUID
}

func (q *Queries) ResolveIncident(ctx context.Context, arg ResolveIncidentParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveIncident,
		arg.EndedAt,
		arg.DurationSeconds,
		arg.ExtremeTemperatureCelsius,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
