// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const incidentSummary = `-- name: IncidentSummary :one
SELECT count(*) FILTER (WHERE i.ended_at IS NULL) AS open_count,
       count(*) FILTER (WHERE i.confirmed_at >= $1::timestamptz) AS recent_count
FROM telemetry.cold_chain_incidents i
JOIN telemetry.shipment_projection p ON p.sscc = i.sscc
WHERE p.participant_tenant_ids @> ARRAY[$2::uuid]
  AND ($3::uuid IS NULL OR p.assigned_driver_id = $3::uuid)
  AND (i.ended_at IS NULL OR i.confirmed_at >= $1::timestamptz)
`

type IncidentSummaryParams struct {
	Since    time.Time
	TenantID uuid.UUID
	DriverID *uuid.UUID
}

type IncidentSummaryRow struct {
	OpenCount   int64
	RecentCount int64
}

// Open incidents, and incidents confirmed since a time, of the shipments that a tenant takes part in.
func (q *Queries) IncidentSummary(ctx context.Context, arg IncidentSummaryParams) (IncidentSummaryRow, error) {
	row := q.db.QueryRow(ctx, incidentSummary, arg.Since, arg.TenantID, arg.DriverID)
	var i IncidentSummaryRow
	err := row.Scan(&i.OpenCount, &i.RecentCount)
	return i, err
}

const shipmentIncidents = `-- name: ShipmentIncidents :many
SELECT i.id, i.sscc, i.shipment_id, i.device_id, i.started_at, i.confirmed_at, i.ended_at, i.min_temp_celsius, i.max_temp_celsius, i.trigger_temperature_celsius, i.extreme_temperature_celsius, i.latitude, i.longitude, i.duration_seconds, i.incident_hash, i.created_at, i.updated_at, p.product_name, p.gtin, p.lot_number
FROM telemetry.cold_chain_incidents i
JOIN telemetry.shipment_projection p ON p.sscc = i.sscc
WHERE i.sscc = $1
  AND ($2::uuid IS NULL OR i.id < $2::uuid)
ORDER BY i.id DESC
LIMIT $3
`

type ShipmentIncidentsParams struct {
	Sscc      string
	After     *uuid.UUID
	PageLimit int32
}

type ShipmentIncidentsRow struct {
	TelemetryColdChainIncident TelemetryColdChainIncident
	ProductName                string
	Gtin                       string
	LotNumber                  string
}

// A page of one shipment's incidents, newest first. Incident IDs are time-ordered by start.
func (q *Queries) ShipmentIncidents(ctx context.Context, arg ShipmentIncidentsParams) ([]ShipmentIncidentsRow, error) {
	rows, err := q.db.Query(ctx, shipmentIncidents, arg.Sscc, arg.After, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentIncidentsRow
	for rows.Next() {
		var i ShipmentIncidentsRow
		if err := rows.Scan(
			&i.TelemetryColdChainIncident.ID,
			&i.TelemetryColdChainIncident.Sscc,
			&i.TelemetryColdChainIncident.ShipmentID,
			&i.TelemetryColdChainIncident.DeviceID,
			&i.TelemetryColdChainIncident.StartedAt,
			&i.TelemetryColdChainIncident.ConfirmedAt,
			&i.TelemetryColdChainIncident.EndedAt,
			&i.TelemetryColdChainIncident.MinTempCelsius,
			&i.TelemetryColdChainIncident.MaxTempCelsius,
			&i.TelemetryColdChainIncident.TriggerTemperatureCelsius,
			&i.TelemetryColdChainIncident.ExtremeTemperatureCelsius,
			&i.TelemetryColdChainIncident.Latitude,
			&i.TelemetryColdChainIncident.Longitude,
			&i.TelemetryColdChainIncident.DurationSeconds,
			&i.TelemetryColdChainIncident.IncidentHash,
			&i.TelemetryColdChainIncident.CreatedAt,
			&i.TelemetryColdChainIncident.UpdatedAt,
			&i.ProductName,
			&i.Gtin,
			&i.LotNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibleIncidents = `-- name: VisibleIncidents :many
SELECT i.id, i.sscc, i.shipment_id, i.device_id, i.started_at, i.confirmed_at, i.ended_at, i.min_temp_celsius, i.max_temp_celsius, i.trigger_temperature_celsius, i.extreme_temperature_celsius, i.latitude, i.longitude, i.duration_seconds, i.incident_hash, i.created_at, i.updated_at, p.product_name, p.gtin, p.lot_number
FROM telemetry.cold_chain_incidents i
JOIN telemetry.shipment_projection p ON p.sscc = i.sscc
WHERE p.participant_tenant_ids @> ARRAY[$1::uuid]
  AND ($2::uuid IS NULL OR p.assigned_driver_id = $2::uuid)
  AND ($3::text IS NULL
       OR ($3::text = 'open') = (i.ended_at IS NULL))
  AND ($4::uuid IS NULL OR i.id < $4::uuid)
ORDER BY i.id DESC
LIMIT $5
`

type VisibleIncidentsParams struct {
	TenantID  uuid.UUID
	DriverID  *uuid.UUID
	State     *string
	After     *uuid.UUID
	PageLimit int32
}

type VisibleIncidentsRow struct {
	TelemetryColdChainIncident TelemetryColdChainIncident
	ProductName                string
	Gtin                       string
	LotNumber                  string
}

// A page of the incidents of the shipments that a tenant takes part in, newest first. A driver sees only the
// shipments assigned to it. state is 'open', 'resolved', or NULL for both.
func (q *Queries) VisibleIncidents(ctx context.Context, arg VisibleIncidentsParams) ([]VisibleIncidentsRow, error) {
	rows, err := q.db.Query(ctx, visibleIncidents,
		arg.TenantID,
		arg.DriverID,
		arg.State,
		arg.After,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisibleIncidentsRow
	for rows.Next() {
		var i VisibleIncidentsRow
		if err := rows.Scan(
			&i.TelemetryColdChainIncident.ID,
			&i.TelemetryColdChainIncident.Sscc,
			&i.TelemetryColdChainIncident.ShipmentID,
			&i.TelemetryColdChainIncident.DeviceID,
			&i.TelemetryColdChainIncident.StartedAt,
			&i.TelemetryColdChainIncident.ConfirmedAt,
			&i.TelemetryColdChainIncident.EndedAt,
			&i.TelemetryColdChainIncident.MinTempCelsius,
			&i.TelemetryColdChainIncident.MaxTempCelsius,
			&i.TelemetryColdChainIncident.TriggerTemperatureCelsius,
			&i.TelemetryColdChainIncident.ExtremeTemperatureCelsius,
			&i.TelemetryColdChainIncident.Latitude,
			&i.TelemetryColdChainIncident.Longitude,
			&i.TelemetryColdChainIncident.DurationSeconds,
			&i.TelemetryColdChainIncident.IncidentHash,
			&i.TelemetryColdChainIncident.CreatedAt,
			&i.TelemetryColdChainIncident.UpdatedAt,
			&i.ProductName,
			&i.Gtin,
			&i.LotNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
