// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type TelemetryColdChainIncident struct {
	ID                        uuid.UUID
	Sscc                      string
	ShipmentID                uuid.UUID
	DeviceID                  string
	StartedAt                 time.Time
	ConfirmedAt               time.Time
	EndedAt                   *time.Time
	MinTempCelsius            float64
	MaxTempCelsius            float64
	TriggerTemperatureCelsius float64
	ExtremeTemperatureCelsius float64
	Latitude                  float64
	Longitude                 float64
	DurationSeconds           *int32
	IncidentHash              string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}
